name: release

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.8","3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install setuptools wheel
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install packages
      run: python -m pip install -r requirements.txt

    - name: Encrption Code
      run: |
            echo -Process: ls
            ls 
            
            echo -Process: ls encryption
            ls encryption
            
            echo -Process: cp setup.py
            cp encryption/setup.py algodojo
            
            echo -Process: cd algodojo
            cd algodojo
            
            echo -Process: ls
            ls
            
            echo -Process: encryption file2
            python setup.py build_ext --inplace
            
            echo -Process: ls
            ls
    # - name: Build binary wheel
    #   shell: cmd
    #   run: bdist_wheel.bat

    # - name: Archive dist artifacts
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: dist-windows-${{ matrix.python-version }}
    #     path: algodojo