# This is a basic workflow to help you get started with Actions

name: Algodojo_CI

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        # run: |
          # echo Add other actions to build,
          # echo test, and deploy your project.

      # - name: Set up Python all python version
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     architecture: x64
      # - name: Install package
      #   run: python -m pip install ibapi
      
      # - name: UnitTest_IB
      #   run: python -m unittest test_ib.py

      # - name: Get github ip
      #   run: python ip.py

      # - name: Encrption Source Code
      #   shell: cmd
      #   run: encryption.bat

      - name: Install package
        run: pip install -r requirements.txt