name: release

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install build tools and cython
      run: |
            python -m pip install setuptools wheel build twine cython

    # - name: Cythonize Python files
    #   run: cythonize -i src/dojotest

    - name: Build the package
      run: python -m build

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-${{ matrix.python-version }}
        path: dist

  upload:
    needs: [build-windows]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.11"
        cache: 'pip'
        
    - name: Install dependencies
      run: |
            mkdir dist

    - name: Install build tools
      run: python -m pip install --upgrade pip setuptools wheel build twine 

    - name: Stage windows 3.11
      uses: actions/download-artifact@v1
      with:
        name: dist-windows-3.11
    - run: mv -v dist-windows-3.11/* dist

    - name: List build artifacts
      run: ls -l dist/

    - name: Upload with twine
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        python -m twine upload --repository testpypi dist/*
